telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://6884-188-123-231-206.eu.ngrok.io"
  bot-name: "@ZnanieHakaton_bot"
  bot-token: "5392759664:AAHEkXB9ucZ7hl0uv-4LU4kjv37Bb1dxpA0"
